apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-hello-world
  namespace: default
spec:
  selector:
    matchLabels:
      app: docker-hello-world
  template:
    metadata:
      labels:
        app: docker-hello-world
    spec:
      containers:
      - image: swr.cn-east-3.myhuaweicloud.com/batch/docker-hello-world:<BUILD_TAG>
      - port:
          containerPort: 80           
        name: docker-hello-world
        env:
        - name: branch
      imagePullSecrets:
        - name: default-secret
