apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: swr.ap-southeast-3.myhuaweicloud.com /batch/docker-hello-world:<BUILD_TAG>
        ports:
          - containerPort: 80        
        imagePullPolicy: IfNotPresent
        command:
          - sleep
        args:
          - '1000'
        name: jenkins-demo
        env:
        - name: branch
      imagePullSecrets:
        - name: default-secret
